### ISSUE TITLE
AttributeError: 'SQLLeaguePosition' object has no attribute 'delete'

### ISSUE THREAD

**Issue by bmon** [meraki-analytics/cassiopeia-datastores#12]
Hi,

While storing some matches + league position data I encountered the following exception. It looks like [the code](https://github.com/meraki-analytics/cassiopeia-datastores/blob/master/cassiopeia-sqlstore/cassiopeia_sqlstore/SQLStore.py#L499) is trying to clean out old data from the sql store but the delete method is not implemented. I can't seem to find any other references to a `delete()` call.

I'm happy to make a pull to fix this, but I'm not sure what the desired behavior is.

```
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/brendanroy/git/rito-nn/worker.py", line 54, in run
    for league in part.summoner.league_positions:
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/merakicommons/container.py", line 354, in __iter__
    yield next(self)
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/merakicommons/container.py", line 365, in __next__
    value = next(self._generator)
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/cassiopeia/datastores/ghost.py", line 569, in league_entries_generator
    data = context[context.Keys.PIPELINE].get(LeaguePositionsData, query)
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/datapipelines/pipelines.py", line 459, in get
    return handler.get(query, context)
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/datapipelines/pipelines.py", line 190, in get
    sink.put(result, context)
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/datapipelines/pipelines.py", line 140, in put
    self._sink.put(self._store_type, item, context)
  File "/Users/brendanroy/.pyenv/versions/3.6.5/lib/python3.6/site-packages/datapipelines/sinks.py", line 62, in wrapper
    return call(self, items, context=context)
  File "/Users/brendanroy/git/rito-nn/src/cassiopeia-sqlstore/cassiopeia-sqlstore/cassiopeia_sqlstore/SQLStore.py", line 499, in put_league_positions
    old_positions[i].delete()
AttributeError: 'SQLLeaguePosition' object has no attribute 'delete'
```

**Comment by jjmaldonis** [comment]
League/LeaguePosition data is pretty weird to work with. There are some edge cases that need to be handled correctly. Hopefully me, you, or @Satrium can think about this when one of us gets a chance. I don't know off the top of my head what we need to do because I haven't thought about it in a while. We'll also need to be careful not to be modifying the list we are iterating over in the line of code you linked (right now it looks like it will skip some elements in the list if something is deleted).

**Comment by Satrium** [comment]
I'm currently not at home, but I should have some time next week to take a
look at this issue.

Jason Maldonis <notifications@github.com> schrieb am Di., 31. Juli 2018,
18:04:

**Comment by jjmaldonis** [comment]
@Satrium cool sounds good if you get some time later on! In the mean time I'll try to think about it a bit. Enjoy and talk to you when you get back!

**Comment by Satrium** [comment]
Because I'm currently on vacation i don't have a development environment setup, so can't test if this is working, but i think this
https://github.com/meraki-analytics/cassiopeia-datastores/blob/98e8b26a53c852547b083c1c648cba1c8d84ffa4/cassiopeia-sqlstore/cassiopeia_sqlstore/SQLStore.py#L499
should be
```python
self._session().delete(old_positions[i])
```
would be nice if someone could test that.
